name: tango
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - traci
      - sumolib
      - lxml
      - dash
      - plotly
      - pyproj
      - pandas
      - numpy
      - pyarrow
      - openpyxl
      - requests
      - jupyter
      - matplotlib
      - seaborn
      - geopandas
      - shapely
